### ISSUE TITLE
Unable to signin

### ISSUE THREAD

**Issue by subodhk01** [IIT-BHU-InstiApp/IIT-BHU-app#130]
When trying to google login
```dart
google sign in error: PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 10: , null)
```
Is it me lacking any secret key or something for the API ???

**Comment by mohit-mangal** [comment]
@subodhk01  is your SHA-1 key added to firebase, without that you won't be able to debug app, but still can use released apk

**Comment by subodhk01** [comment]
I added my SHA1 key to the firebase console but now on the POST request to workshops backend I'm getting Invalid firebase token.
<img width="855" alt="Screenshot 2020-05-08 at 21 24 55" src="https://user-images.githubusercontent.com/19875783/81423650-5e24f100-9172-11ea-993e-5c73a5e6894a.png">

**Comment by nishantkr18** [comment]
> I added my SHA1 key to the firebase console but now on the POST request to workshops backend I'm getting Invalid firebase token.

not sure why that is.. Can u share the code? btw, just to be clear, u've performed [these](https://developers.google.com/android/guides/client-auth) steps right? and had your SHA key added in firebase console by one of us?

**Comment by priyanshnama** [comment]
may i work on it

**Comment by mohit-mangal** [comment]
> may i work on it

Actually, i have no problem but you need to have a gmail account with iitbhu credentials for authorization in app. You can bypass the gmail auth but not the backend.

**Comment by priyanshnama** [comment]
ohh okk.... no problem.
