### ISSUE TITLE
Code cleaning (`AppConstants.dart) 

### ISSUE THREAD

**Issue by nishantkr18** [IIT-BHU-InstiApp/IIT-BHU-app#179]
`IIT-BHU-app/lib/model/appConstants.dart` needs proper restructuring.

**Comment by nishantschavan** [comment]
@nishantkr18 what do you mean by restructuring?

**Comment by Siddhant-K-code** [comment]
@nishantkr18 please elaborate on your issue, so we can work on it

**Comment by nishantkr18** [comment]
sorry for the delayed response. I guess @mohit-mangal can provide a better insight.. If you are interested, you can join the telegram grp https://t.me/joinchat/OBBhNRXt6GqQjEFzMjDIVw

**Comment by mohit-mangal** [comment]
Has been done.
