### ISSUE TITLE
Clicking on a Contact throws an exception

### ISSUE THREAD

**Issue by Vikhyath08** [IIT-BHU-InstiApp/IIT-BHU-app#184]
When browsing a workshop, tapping a contact from the list of contacts throws the following exception.

════════ Exception caught by widgets library ═══════════════════════════════════
The following assertion was thrown building Builder(dirty):
A non-null String must be provided to a Text widget.
'package:flutter/src/widgets/text.dart':
Failed assertion: line 370 pos 10: 'data != null'

**Comment by mohit-mangal** [comment]
@Vikhyath08 
Have you fixed this ?
This exception tells that one of String variable is null inside Contact Model.
