### ISSUE TITLE
Redundant code in built_post.dart

### ISSUE THREAD

**Issue by Vikhyath08** [IIT-BHU-InstiApp/IIT-BHU-app#207]
Isn't having two separate classes for `TagSearch` and `TagDetail` redundant?
As the type is same, it could be served by just having a single class.
One could also stretch this as far as `TagCreate`, as the syntax of all the three are identical, but the use of `TagCreate` is different.

**Comment by mohit-mangal** [comment]
Yes you are right, we made it this way in hurry and also to reduce ambiguity. You can clean that and put a name of one model which doesn't indicate any specific behaviour.
