### ISSUE TITLE
Incorrect confirmation message for DeleteWorkshop

### ISSUE THREAD

**Issue by Vikhyath08** [IIT-BHU-InstiApp/IIT-BHU-app#208]
Deleting a workshop gives the same confirmation message as creating.
This can be changed [here](https://github.com/IIT-BHU-InstiApp/IIT-BHU-app/blob/master/lib/screens/home/worshop_detail/workshop_detail.dart#L321) and [here](https://github.com/IIT-BHU-InstiApp/IIT-BHU-app/blob/master/lib/screens/home/worshop_detail/workshop_detail.dart#L237) by editing the function to accept create or delete parameters.
Alternatively, this can be done by creating a separate dialog box function for deletion, similar to the one for creation.

**Comment by nb9960** [comment]
> Deleting a workshop gives the same confirmation message as creating.
> This can be changed [here](https://github.com/IIT-BHU-InstiApp/IIT-BHU-app/blob/master/lib/screens/home/worshop_detail/workshop_detail.dart#L321) and [here](https://github.com/IIT-BHU-InstiApp/IIT-BHU-app/blob/master/lib/screens/home/worshop_detail/workshop_detail.dart#L237) by editing the function to accept create or delete parameters.
> Alternatively, this can be done by creating a separate dialog box function for deletion, similar to the one for creation.

@Vikhyath08 I have already corrected this in #203

**Comment by Vikhyath08** [comment]
Oh. Okay.
I'll close the issue when the PR is merged @nb9960 .
