### ISSUE TITLE
Adding options to refresh in pages

### ISSUE THREAD

**Issue by Vikhyath08** [IIT-BHU-InstiApp/IIT-BHU-app#249]
As of now, the pull-to-refresh option is pending in these pages:
- [x] All Workshops and Events
- [x] All Entities and Fests
- [x] Your Interests

**Comment by mohit-mangal** [comment]
Apart from setState, use fetchFunctions defined in respective pages.

**Comment by mohit-mangal** [comment]
Resolved!!!
