### ISSUE TITLE
Replace all deprecated widgets (showSnackBar and RaisedButton)

### ISSUE THREAD

**Issue by nb9960** [IIT-BHU-InstiApp/IIT-BHU-app#299]

**Comment by dev-raj-1729** [comment]
Hey I would like to work on this

**Comment by Vikhyath08** [comment]
Sure. It's all yours!

**Comment by epselon007** [comment]
hey i would like to work on this.

**Comment by Vikhyath08** [comment]
Someone's already started work on this 😅. You can pick another issue, or go through the app to find an issue of your own to work on. Make sure you create the issue and mention that you're going to work on it before getting started!

**Comment by dev-raj-1729** [comment]
While migrating the buttons (FlatButton, Raised Button, Outline Button) should I preserve their appearances? (The new ones inherits defaults from textTheme and ColorScheme while the deprecated ones do not)

**Comment by dev-raj-1729** [comment]
this change primarily affects the color of the button

**Comment by nb9960** [comment]
> While migrating the buttons (FlatButton, RaisedButton, OutlineButton), should I preserve their appearances? (The new ones inherits defaults from textTheme and ColorScheme while the deprecated ones do not)

Yes, appearance shouldn't be affected. New ones have somewhat other options to set the theme like for OutlinedButton, you have OutlinedButtonTheme, instead of the usual ButtonTheme that was in deprecated OutlineButton. Refer to : [Migrating to the New Material Buttons and their Themes](https://docs.google.com/document/d/1yohSuYrvyya5V1hB6j9pJskavCdVq9sVeTqSoEPsWH0/edit?usp=sharing)

**Comment by dev-raj-1729** [comment]
I have submitted a pull request with changes fixing the issue
