### ISSUE TITLE
TO DO

### ISSUE THREAD

**Issue by nishantkr18** [IIT-BHU-InstiApp/IIT-BHU-app#6]
- [ ] **notification** for every new workshop created.

- [ ] add image_picker and use in workshop create page.
- [x] To change initial date and last date for **date_picker** (currently fixed to 2018 and 2022 resp.)

- [x] to add feilds in workshop detail view
- [x] workshop update through patch request
- [x] profile details update through patch
- [x] adding refresh option for home page
- [x] make + for creating Workshops, available only for admin user.
- [x] past workshops visible

- [x] add location option in workshop create page.
- [x] add delete functionality of user created workshops in Account screen.
- [x] show id admin or not in the Account screen.
- [x] add going response of each user for each workshop.

* - [x] add a councils screen and represent each club in that council along with details of the Gen Secys.
* - [x] Each club, on clicking, will open its page.
* - [x] That page will have its details, current Secys, all workshops of that club, Achievements of that club.
- [x] show snackbak at transition from login to home screen.
- [x] show proper loading effect in workshop cards.
- [x] replace create workshop with + in home page.
- [x] add logout option on profile photo.
- [x] add exit confirm.
- [x] redirect to homescreen if previously logged in(save the state of the app).

#### Endpoints to use:
- [x] GET workshop/id 
- [x] GET workshop/past
- [x] GET clubs/{id}/toggle-subscribed/

**Comment by nishantwrp** [comment]
Do you update this?

**Comment by nishantkr18** [comment]
> Do you update this?

Nope, need to
