### ISSUE TITLE
FabCircularMenu

### ISSUE THREAD

**Issue by nishantkr18** [IIT-BHU-InstiApp/IIT-BHU-app#82]
The menu should automatically close on clicking anywhere else other than the options on menu.
It should also close on pressing back.

**Comment by yashjain715-creater** [comment]
Anywhere means on search bar, on click workshop, on click drawer, except menu options

**Comment by nishantkr18** [comment]
Yeah, everywhere except the button which opens the FabCircularMenu.

**Comment by yashjain715-creater** [comment]
After open fab circular menu cross icon show, then it not allow to close
